# From https://gist.github.com/vidavidorra/548ffbcdae99d752da02

# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: libxmldiff
    - DOXYFILE: $TRAVIS_BUILD_DIR/doc/libxmldiff.dox
    - GH_REPO_REF: github.com/rpeyron/libxmldiff.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - ./configure

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x travis_dox.sh
  - ./travis_dox.sh